### ISSUE TITLE
drupal/entity marked insecure?

### ISSUE THREAD

**Issue by Boegie** [Roave/SecurityAdvisories#54]
I see that since yesterday you've added Drupal Contrib Modules to your great package.

I like that, but it currently breaks my composer on all my D8-projects, because _all_ versions of drupal/entity are marked as unsafe:` "drupal/entity": ">=1,<1.9"`

At least the latest (1.0-rc1) version has been found safe by the Drupal Security Team: https://www.drupal.org/project/entity

**Comment by Ocramius** [comment]
Please see https://github.com/FriendsOfPHP/security-advisories/pull/371 - this package only syncs from there.

**Comment by Boegie** [comment]
Thanks you for the quick reply.

At FriendsOfPHP they at least make a distinction between Drupal 7 and Drupal 8

I use your package with Drupal 8, but the drupal/entity SA warning is for Drupal 7 (see line 7 on https://github.com/FriendsOfPHP/security-advisories/blob/master/drupal/entity/sa-contrib-2018-013.yaml)

The way your composer.json is currently setup breaks all my Composer builds for D8 for a D7 module.
I would be sad to abandon it, but without any distinction in Drupal 7 and Drupal 8 there's no other choice for me (and if I'm correct) for any Drupal Developer.

**Comment by Ocramius** [comment]
The `composer.json` is really only generated from upstream constraints: you'll need to check if the upstream manifests have valid constraints, and send a patch there (assuming the security issues were solved)

**Comment by Boegie** [comment]
Thanks for the explanation, we've opted to switch to a package which differentiates between D7 and D8 by default: https://github.com/drupal-composer/drupal-security-advisories

**Comment by Ocramius** [comment]
Uhh, that smells like upstream advisory ranges are just broken (already at the source, in drupal).

You shouldn't need different advisory sets depending on your project: there's only one pool of advisories...

**Comment by Boegie** [comment]
Undoubtedly, but swapping out the roave package from my 20+ Drupal
composer.json is a lot quicker than battling that one out :)

Thanks again.

**Comment by Ocramius** [comment]
Yeah, but that's not solving the root cause, and will lead more folks to follow this broken approach.

Either a package version is affected by a security advisory or it is not: there is no "depends".

Therefore, if you can, see if the ranges reported upstream are to be adjusted, because some other folks will have similar issues.

**Comment by colinodell** [comment]
The ranges reported upstream are correct **but they only apply to versions from that particular registry**.  For example, due to this line in https://github.com/FriendsOfPHP/security-advisories/blob/master/drupal/entity/sa-contrib-2018-013.yaml...

```yaml
composer-repository: 'https://packages.drupal.org/7'
```

This advisory is only for `drupal/entity` if installed from that registry.

This is an important distinction because Drupal maintains two separate Composer registries for Drupal 7 and Drupal 8 modules:

 - https://packages.drupal.org/7 for Drupal 7 modules
 - https://packages.drupal.org/8 for Drupal 8 modules

Over on "Drupal Island" they use non-semver prefixes for their version numbers and tags:

 - `7.x-` for Drupal 7 modules
 - `8.x-` for Drupal 8 modules

For example, the first 1.0 RC would have tags like this in Git:

 - 7.x-1.0-rc1
 - 8.x-1.0-rc1

(See https://cgit.drupalcode.org/entity/refs/ for an example of drupal/entity's git tags)

When exposing these releases to Composer, Drupal uses that prefix to determine which repository it goes in, and then removes that prefix.  In the example above, both versions will satisfy a Composer constraint of  `1.0@RC` but you'll get a completely different "major version" depending on which registry you're using - the D7 one or the D8 one.

As a result, the constraint of `"drupal/entity": ">=1,<1.9"` ends up blocking installation of both "major versions" even though the advisory only applies to one registry and not the other.

It seems to me that the upstream information is correct **but the approach used here is not capable of differentiating between dependencies installed from different registries**.  If that is indeed the case, perhaps this repository should exclude any packages where the upstream `composer-repository` value is not false?  Or perhaps a Composer plugin-based approach would be needed to properly block installation based on the registry used?

**Comment by Ocramius** [comment]
Oh, I see, so the ecosystem releases are completely split. That's indeed very messy, and goes against the assumption of this package (packagist being the authoritative source/registry).

That's good to know, and it is indeed good to point people to the Drupal advisories then. That's still a massive fracture in the ecosystem though :-\

**Comment by Boegie** [comment]
Just to be sure @Ocramius: 

Will you be removing the Drupal Contrib Packages from your module (and please keep `drupal/core`) or will the "Drupal Island" suffer from a tsunami of non-building sites if you decide to keep them in?

**Comment by Ocramius** [comment]
No, I plan to keep this  package in sync with `friendsofphp/security-advisories`. If the problem is really there, it should be handled in upstream too. 

If Drupal contrib is its own special world with its own rules, then please make upstream maintainers aware of it at FriendsOfPHP/security-advisories#371, and let's fix it for good.

This package is designed to work with the packagist ecosystem anyway, not with any forks of it.

**Comment by Boegie** [comment]
All clear, thank you for your great work on this package.

**Comment by colinodell** [comment]
Yeah I completely agree.  There are even some cases like `drupal/coder` which is available from both Packagist **and** the two Drupal registries:

 - **Packagist:**
   - `8.3.1` points to [8.x-3.1](https://cgit.drupalcode.org/coder/tag/?id=8.x-3.1)
   - `7.2.5` points to [7.x-2.5](https://cgit.drupalcode.org/coder/tag/?id=7.x-2.5)
 - **https://packages.drupal.org/7**:
   - `2.5` points to [7.x-2.5](https://cgit.drupalcode.org/coder/tag/?id=7.x-2.5)
- **https://packages.drupal.org/8**:
   - `3.1` points to [8.x-3.1](https://cgit.drupalcode.org/coder/tag/?id=8.x-3.1)

So hypothetically, if a security issue was found in `7.x-2.5`, a constraint blocking `<=7.2.5` from the Packagist registry would inadvertantly block all versions from the Drupal registries.  Fun stuff!

----

Backstory time!

The Drupal community used to use a single, community-maintained registry at `packagist.drupal-composer.org` where the major versions were `7` for Drupal 7.x and `8` for Drupal 8.x.  Using the example above you'd therefore have `8.3.1` and `7.2.5` in the same registry and `roave/security-advisories` would work as expected. 

At some point Drupal.org decided they wanted to manage their own official registries instead of the community, and thus the two separate repositories were created and [everyone was asked to migrate to them](https://www.drupal.org/docs/develop/using-composer/using-packagesdrupalorg#convert-endpoints-from-unoffical).

---

Anyway, looking at the upstream advisories, it seems there are currently only four values in use for `composer-repository`:

 - `false`
 - `'https://packages.drupal.org/7'`
 - `'https://packages.drupal.org/8'`
 - the key is not present in the yaml file

So I'm thinking it should be safe to only include yaml advisories where `composer-repository` is missing or `false`.

(`drupal/core` and `drupal/drupal`, which are available via Packagist and use "correct" versioning, have no such key and would therefore still be included as expected)

**Comment by colinodell** [comment]
> If Drupal contrib is its own special world with its own rules, then please make upstream maintainers aware of it at [FriendsOfPHP/security-advisories#371](https://github.com/FriendsOfPHP/security-advisories/pull/371), and let's fix it for good.
>
> This package is designed to work with the packagist ecosystem anyway, not with any forks of it.

Assuming that the upstream maintainers are aware, and thus why `composer-repository` is being used, I do think my suggestion above would fit with how this package should only work with the packagist ecosystem, and would do so without causing negative side effects for people forced to use other registries/repositories/whatever they are called.

Just my $0.02 :)

**Comment by Ocramius** [comment]
Hmm, so the suggestion is to filter out anything coming from custom repositories? Are these packages not published on packagist at all?

**Comment by Boegie** [comment]
> Just my $0.02 :)

Would love to double that money by adding my $0.02.

- This package is widely used in the Drupal Community (for a good reason, because it's good!)
- Basically any Drupal composer manage site (which is the current best practice in Drupal 8) will _not_ build any more after including the Contrib Modules since roughly 12 hours ago.
- @colinodell's solution seems workable, otherwise simply(?) _undoing_ the adding the Drupal Contrib Module specific changes would make it all workable for the Island Drupal inhabitants.

I can understand your POV, but hope that you're willing to reconsider

**Comment by Ocramius** [comment]
> Are these packages not published on packagist at all?

^ this is what calls the shots ^

**Comment by colinodell** [comment]
> Hmm, so the suggestion is to filter out anything coming from custom repositories?

Yep exactly!

> Are these packages not published on packagist at all?

A small number of them, like [drupal/coder](https://packagist.org/packages/drupal/coder), are available on Packagist too.  The overwhelming majority are not.

If this suggestion is implemented, and a package is available from both Packagist.org and some other place, then the person submitting the advisory upstream should submit two advisories - one for the custom `composer-repository` and another without it.  This would ensure that `composer-repository` has the correct value per https://github.com/FriendsOfPHP/security-advisories/issues/127  Not only does this keep the upstream data correct, it would also allow this project to continue working as expected.

**Comment by Ocramius** [comment]
Well, if some of those are published on packagist, the safe default would be to include them here (yes, at the cost of somebody having to migrate away).

What should probably be done is adding all relevant packagist distribution channels to upstream advisories, and then we can filter here.

**Comment by stof** [comment]
@colinodell can you upload your composer.lock file on https://security.symfony.com/ ? If you also get a vulneraibility report there, it means that the inclusion of drupal-contrib advisories created a mess upstream too.

**Comment by Ocramius** [comment]
Another solution is to add a build step that filters out any packages that couldn't be found on packagist.

Meanwhile, re-opening here, as there is indeed work to be done.

**Comment by stof** [comment]
@Ocramius if this also affects usage of https://security.symfony.com/ I think the solution would have to be handled at the level of https://github.com/FriendsOfPHP/security-advisories. That's why I'm asking for confirmation (and I don't have a composer.lock file using drupal/entity so it is easier to ask than to check myself)

**Comment by Boegie** [comment]
@stof Uploaded a composer.lock with drupal/entity on https://security.symfony.com/

It reported `No vulnerabilities detected ... for now!`

The same composer.json with roave/securityadvisories added as as dev-dependency will not allow a build because the Drupal 8 version 1.9 of drupal/entity is marked as unsafe by the "drupal/entity": ">=1,<1.9" which is only for the Drupal 7 version.

**Comment by Ocramius** [comment]
So upstream is filtering correctly: I'll try mimicking it in `Roave/SecurityAdvisoriesBuilder` then

**Comment by colinodell** [comment]
To briefly update my notes about this `composer-repository` key:

 - If this key is missing it means the repository is Packagist (see https://github.com/FriendsOfPHP/security-advisories/blob/6d386c4/validator.php#L118)
 - If the key is present with `false` it means the repository is **not Packagist** and not provided (see https://github.com/FriendsOfPHP/security-advisories/pull/128#issuecomment-276320317)
 - If the key is present with a string value, that provides an alternate repository URL like those given for Drupal 7 & 8 (see https://github.com/FriendsOfPHP/security-advisories/blob/6d386c4/validator.php#L123)

**Comment by Ocramius** [comment]
I wish there was an XSD for this kind of shit :-P

Alright, I'll get to it once up (lazy day)

**Comment by vijaycs85** [comment]
>perhaps this repository should exclude any packages where the upstream `composer-repository` value is not false?
@colinodell this means we would lose coverage for all Drupal contributed modules :(

**Comment by Ocramius** [comment]
@vijaycs85 if Drupal has its own world, it is correct to exclude it from a blacklist designed for a different one.

**Comment by vijaycs85** [comment]
Alright, I have raised a [request](https://github.com/Roave/SecurityAdvisories/issues/54) on `drupal/entity` to clone `8.x-1.x` version to `8.x-2.x` so that at least works for now(some packages followed this when migrated from core 7.x to 8.x).

**Comment by stof** [comment]
According to https://github.com/FriendsOfPHP/security-advisories/issues/373#issuecomment-466965495 I think https://security.symfony.com/ is also affected by this issue, but the new advisories were not deployed yet at the time @colinodell made the test.
@colinodell can you retest it to confirm ?

**Comment by vijaycs85** [comment]
cross posting from https://github.com/FriendsOfPHP/security-advisories/issues/373
>probably because of the `drupal/entity` version. The 8.x version is `1.0-rc1` and the 7.x SA is only between `1.0.0` and `1.9.0`

**Comment by colinodell** [comment]
@stof after re-testing, I can confirm that https://security.symfony.com/ is also affected by this issue.

In my case, I uploaded a `composer.lock` file which installed the Drupal 8 version of `drupal/bootstrap`: version `8.x-3.13` (aka `3.13` in the D8 repo).  This version does not have any known security issues.  However, because the Drupal 7 version had a security update release of `7.x-3.22` (aka `3.22` in the D7 repo), this was incorrectly flagged as insecure.

**Comment by gaelg** [comment]
Hi, I'm one of the "Drupal island" guys :) We use Roave/SecurityAdvisories to make sure we have no non-Drupal security vulnerabilities, in external libraries required by Drupal contrib code. For the Drupal part, we indeed have other ways to check for vulnerabilities, including drupal-composer/drupal-security-advisories.
If I'm right, we're currently waiting for @Ocramius to push a new commit that will fix the problem we face. Meanwhile, what's the best way to update our composer project? Should we remove Roave/SecurityAdvisories from our project as long as this is not fixed (and then lose its benefits) ? Or is there a smarter thing to do?

**Comment by stof** [comment]
@gaelg the solution will probably come from upstream, as the whole ecosystem built on top of [FriendsOfPHP/security-advisories](https://github.com/FriendsOfPHP/security-advisories) actually got affected

**Comment by Ocramius** [comment]
I'm fixing the advisories builder too, BTW. Will take me a few hours.

**Comment by stof** [comment]
@Ocramius if the upstream PR is reverted, is there anything to fix on your side in the builder ?

**Comment by Ocramius** [comment]
@stof yes, according to https://github.com/Roave/SecurityAdvisories/issues/54#issuecomment-466660491

**Comment by stof** [comment]
@Ocramius the Symfony checker does not take this repository into account when validating a composer.lock either. The previous analysis assuming that the Symfony tool was doing smart things was wrong. It was simply that the new drupal contrib advisories were not deployed yet or that the wrong version was used to test, as highlighted by the later check in https://github.com/Roave/SecurityAdvisories/issues/54#issuecomment-467219080

The `composer-repository` key in the advisory is only used by the CI: the validator script validates the package name against the provided repository (defaulting to Packagist) unless it is set to `false`. The goal being to avoid typos in package names (which would make advisories useless).

**Comment by Ocramius** [comment]
Which means that in both cases the metadata is correct, but the validation is not :+1:

**Comment by stof** [comment]
no, which means that the author had different expectations over `composer-repository`, making the advisory validation take represent packages as `repo + name + version` instead of only `name + version`. The current validation is consistent with the Composer behavior, so I would say it is wrong.

The root cause of the issue here is that the Drupal ecosystem breaks one of the composer assumptions (which would create a *huge* mess if both repos are enabled at the same time). And the solution here would IMO be to let them use their own advisory database for packages belonging there.

**Comment by Ocramius** [comment]
I can agree with that: since Drupal is not part of https://packagist.org/ (in this set of dependencies), it most likely shouldn't be in upstream dependencies either, unless we want to start documenting other repositories too.

**Comment by stof** [comment]
Well, the existing policy in [FriendsOfPHP/security-advisories](https://github.com/FriendsOfPHP/security-advisories) is to accept other packages too, when things are sensible. The drupal contrib weirdness makes them out of that category IMO.

For an ecosystem which uses their own repository but keeps the invariant that a composer package gets uniquely identified by `name + version`, there is no issue at all about having them in that database and in your conflict rules.

**Comment by Ocramius** [comment]
As per https://github.com/Roave/SecurityAdvisories/commit/ff1020e24967e525adf76ebf9c28a14601d6fc8c, drupal contrib is no longer in here.

**Comment by Boegie** [comment]
Thanks for the hard work @Ocramius

**Comment by Ocramius** [comment]
All work so far was done by @fabpot and @stof

**Comment by gaelg** [comment]
Thank you anyway, work is not limited to commits. ;)
