### ISSUE TITLE
Conflict with cakephp fork

### ISSUE THREAD

**Issue by garethellis36** [Roave/SecurityAdvisories#77]
We have forked CakePHP because we have several applications still going strong on the v2 line, which is now EOL. We wanted to update it to support PHP 8, so we forked it, got the tests passing on PHP 8, and now want to require it in our applications.

Just to confuse everyone further, we dropped all the Cake versioning and started our own semver again.

However, when I try to require it, I get:

```
  Problem 1
    - roave/security-advisories is locked to version dev-master and an update of this package was not requested.
    - roave/security-advisories dev-master conflicts with myorg/cakephp 1.1.0.
    - Root composer.json requires myorg/cakephp ^1.1 -> satisfiable by myorg/cakephp[1.1.0].
```

I notice that `cakephp/cakephp` `<1.3.18` is in the list of packages in the `conflict` list of this repository. Is that causing this issue?

Our fork is in a repository on Private Packagist, and the only things in its own `require` are PHP, PHPUnit (v8), and Rector prefixed.

I guess this might be a composer (or a user understanding) problem rather than a `roave/securityadvisories` problem, but thought I'd ask for advice. Cheers!

**Comment by Ocramius** [comment]
does `myorg/cakephp` `"replace"` or `"provide"` cakephp?

If that's the case, then `myorg/cakephp` is effectively an alias of the upstream cakephp to the eyes of composer's SAT internals.

**Comment by garethellis36** [comment]
Yes, it `replace`s it. I've removed that and it's installing OK now. Thanks Marco 👍

**Comment by LukeTowers** [comment]
@bennothommo on an unrelated note since I don't think I've come across `provide` before, would it make more sense for our internal processes to use `provide` instead of `replace` when building the marketplace plugins for @wintercms?

**Comment by Ocramius** [comment]
@LukeTowers I think `provide` has the same issue - you need to be more restrictive on the precise version you provide (I think `provide` is generally much stricter)

**Comment by LukeTowers** [comment]
Gotcha, thanks for the input @Ocramius. We use the feature to inject the list of dependencies that are included in a base @wintercms install when we're generating the embedded vendor directory of plugins available via the @wintercms marketplace so that the vendor folder of plugins don't include any dependency duplicates that would already be present in any project using the plugin. Ultimately I guess it doesn't really matter for our use case which one we use then, although I think replace is less of a headache to deal with for our needs.
